--[[
* BlueMage - Blue Magic spell-learning tracker (HorizonXI)
*
* The tracker module for the standalone BlueMage addon. Bound to the addon
* host (bluemage.lua) via M.init(host). Window settings (lock, hide-on-menu,
* BG color, open state, filter toggles) come from the host's cfg under the
* `bluemage_*` namespace. Per-character learned state lives under
* cfg.bluemage_data.learned (key -> bool), which is persisted by the settings
* library (settings are per-character in Ashita, so learned Blue Magic is
* naturally tracked per character).
*
* The main "Blue Magic" window carries two tabs: "Spells" (this tracker) and
* "Settings" (the config UI). The title-bar gear and `/blutracker config` jump to the
* Settings tab.
*
* The window lists every Blue Magic spell learnable at level 75 and below on
* HorizonXI (a 75-era + "Era+" server). Data comes from data/bluemage_spells.lua,
* which is compiled from the HorizonXI wiki and differs from retail where the
* wiki flags a Horizon-specific change.
*
* Features:
*   - Learned checkmarks are read automatically from the player's Blue Magic
*     spellbook (IPlayer:HasSpell), polled on a throttle so they stay live.
*     They are read-only; there is no manual toggle.
*   - Chat fallback: only if the spellbook read is unavailable, watches chat
*     for the "learns <Spell>" message and marks the spell.
*   - Click a spell name to see where to learn it (monster / level / zone).
*   - Filters: text search, role, trait, learn-from family, hide-learned,
*     and "at or below my level" (uses your BLU main-job level).
*   - A progress bar / counter for overall learning completion.
--]]

local imgui = require('imgui')
local DB    = require('data/bluemage_spells')
local LF    = require('data/bluemage_learnfrom')
local SID   = require('data/bluemage_spellids')   -- key -> FFXI spell id
local MRL   = require('data/bluemage_mrl')         -- key -> min BLU level to learn
local REQSK = require('data/bluemage_reqskill')    -- key -> Blue Magic skill to learn
local ZONES = require('data/bluemage_zones')       -- zone id -> formatted zone name

-- Mob spawn positions for the hover mini-map. World coords (+x=east,+z=south),
-- keyed by zone name -> mob name -> list of {x,z}, with per-zone bounds.
-- Generated by tools/build_mob_positions.py from the LSB server database.
-- MOB POSITIONS ONLY -- no client map artwork is bundled.
local ok_pos, POS = pcall(require, 'data/mob_positions')
if not ok_pos or type(POS) ~= 'table' then POS = {} end

-- Live client-map reader (reads the real zone map from the running game, no
-- bundled art). Guarded: returns nil outside the game so we fall back to grid.
local ok_gm, gamemap = pcall(require, 'src/gamemap')
if not ok_gm then gamemap = nil end

-- "Action Learned!" splash helper (merged from Kalrir's BlueLearn addon).
-- Guarded: if it or its gdifonts library fails to load, the splash is simply
-- unavailable and the rest of the Blue Mage module is unaffected.
local ok_bl, BlueLearn = pcall(require, 'BlueLearn')
if not ok_bl then BlueLearn = nil end

local M = {}

-- Spellbook sync: the learned checkmarks are driven by the player's actual
-- Blue Magic spellbook (IPlayer:HasSpell), not by manual clicks. We poll on a
-- throttle so newly-learned spells / character changes are reflected live.
local spellbook_ok    = true   -- set false if HasSpell isn't usable
local last_sync_frame = 0
local frame_counter   = 0
local SYNC_INTERVAL   = 30      -- frames between spellbook re-scans (~0.5s)

-- Spells sorted ascending by level, then name, for display. The source data is
-- already in level order; sorting makes the default order explicit/guaranteed.
local SORTED = {}
for _, r in ipairs(DB.SPELLS) do SORTED[#SORTED + 1] = r end
table.sort(SORTED, function(a, b)
    if a.lvl ~= b.lvl then return a.lvl < b.lvl end
    return a.name < b.name
end)

-- Currently selected spell (its learn-from detail is shown in the panel).
local selectedKey = nil

-- Set in M.init from host:
local cfg         = nil  -- bound to host.cfg
local vt          = nil  -- bound to host.vt
local settings    = nil  -- bound to host.settings
local helpers     = nil  -- bound to host.helpers
local default_cfg = nil  -- bound to host.default_config

-- Bound subtable of cfg.bluemage_data once init() runs:
local learned = nil   -- key -> bool
local tracked = nil   -- key -> bool (spells the user flagged for the tracker)

-- =========================
-- Constants
-- =========================
local BLU_JOB_ID     = 16
local WINDOW_WIDTH   = 700
local WINDOW_HEIGHT  = 648
local FOOTER_HEIGHT  = 32
local DETAIL_HEIGHT  = 140   -- "Learned From" panel at the bottom

-- Column widths (pixels) for the Columns() table layout.
-- Order: Learned | Trk | MRL | LVL | Spell | Type | Trait | Family
local CW_CHECK = 30
local CW_TRK   = 78
local CW_MRL   = 40
local CW_LV    = 36
local CW_NAME  = 156
local CW_TYPE  = 104
local CW_TRAIT = 130
local CW_FAM   = 82

-- Element / damage-type tint for the Type column (and a faint row accent).
local ELEM_COLORS = {
    Fire     = { 0.95, 0.45, 0.35, 1.0 },
    Ice      = { 0.55, 0.80, 0.98, 1.0 },
    Wind     = { 0.55, 0.90, 0.65, 1.0 },
    Earth    = { 0.85, 0.70, 0.45, 1.0 },
    Thunder  = { 0.80, 0.65, 1.00, 1.0 },
    Water    = { 0.45, 0.70, 0.98, 1.0 },
    Light    = { 0.96, 0.94, 0.70, 1.0 },
    Dark     = { 0.72, 0.60, 0.88, 1.0 },
    Slashing = { 0.80, 0.82, 0.90, 1.0 },
    Blunt    = { 0.80, 0.82, 0.90, 1.0 },
    Piercing = { 0.80, 0.82, 0.90, 1.0 },
    H2H      = { 0.80, 0.82, 0.90, 1.0 },
    Ranged   = { 0.80, 0.82, 0.90, 1.0 },
}

local ROLE_COLORS = {
    Damage   = { 0.90, 0.72, 0.55, 1.0 },
    Heal     = { 0.55, 0.95, 0.60, 1.0 },
    Buff     = { 0.60, 0.85, 1.00, 1.0 },
    Enfeeble = { 0.95, 0.80, 0.50, 1.0 },
    Drain    = { 0.85, 0.55, 0.80, 1.0 },
    Dispel   = { 0.75, 0.80, 0.95, 1.0 },
}

-- =========================
-- Module-level defaults exported for Codex to merge into its
-- default_config under cfg.bluemage_data.
-- =========================
M.default_data = T{
    learned = T{},
}
for _, r in ipairs(DB.SPELLS) do
    M.default_data.learned[r.key] = false
end

-- User-selected "specific" spells to track. Persisted (unlike learned).
M.default_track = T{
    tracked = T{},
}
for _, r in ipairs(DB.SPELLS) do
    M.default_track.tracked[r.key] = false
end

-- Window-level defaults (documentation; the authoritative copy lives in
-- Codex's default_config under the bluemage_* keys).
M.default_window = {
    bluemage_open          = false,
    bluemage_win_x         = 340,
    bluemage_win_y         = 200,
    bluemage_font_scale    = 1.0,
    bluemage_lock_ui       = false,
    bluemage_hide_on_menu  = false,
    bluemage_auto_learn    = true,
    bluemage_hide_learned  = false,
    bluemage_only_my_level = false,
    bluemage_bg_color_r    = 0.06,
    bluemage_bg_color_g    = 0.07,
    bluemage_bg_color_b    = 0.10,
    bluemage_bg_color_a    = 0.96,
}

-- =========================
-- Transient (per-session) filter state
-- =========================
local searchBuf  = { '' }
local roleFilter  = 'All'
local traitFilter = 'All'
local famFilter   = 'All'

-- Tracking modes for the separate tracker window: { cfg value, display label }.
local TRACK_MODES = { { 'off', 'Off' }, { 'specific', 'Specific' }, { 'zone', 'Zone' } }

-- =========================
-- Theme (mirrors the other Codex windows)
-- =========================
local THEME_COLOR_COUNT = 17

local function PushWindowTheme(bg_r, bg_g, bg_b, bg_a)
    imgui.PushStyleColor(ImGuiCol_WindowBg,         { bg_r, bg_g, bg_b, bg_a })
    imgui.PushStyleColor(ImGuiCol_TitleBg,          { 0.18, 0.16, 0.24, 1.00 })
    imgui.PushStyleColor(ImGuiCol_TitleBgActive,    { 0.18, 0.16, 0.24, 1.00 })
    imgui.PushStyleColor(ImGuiCol_TitleBgCollapsed, { 0.18, 0.16, 0.24, 1.00 })
    imgui.PushStyleColor(ImGuiCol_Border,           { 0.28, 0.26, 0.38, 0.90 })
    imgui.PushStyleColor(ImGuiCol_FrameBg,          { 0.14, 0.15, 0.20, 1.00 })
    imgui.PushStyleColor(ImGuiCol_FrameBgHovered,   { 0.18, 0.20, 0.28, 1.00 })
    imgui.PushStyleColor(ImGuiCol_Header,           { 0.22, 0.30, 0.44, 0.65 })
    imgui.PushStyleColor(ImGuiCol_HeaderHovered,    { 0.26, 0.34, 0.52, 0.75 })
    imgui.PushStyleColor(ImGuiCol_Button,           { 0.16, 0.18, 0.26, 1.00 })
    imgui.PushStyleColor(ImGuiCol_ButtonHovered,    { 0.24, 0.28, 0.42, 1.00 })
    imgui.PushStyleColor(ImGuiCol_ButtonActive,     { 0.32, 0.38, 0.58, 1.00 })
    imgui.PushStyleColor(ImGuiCol_CheckMark,        { 0.40, 0.70, 1.00, 1.00 })
    imgui.PushStyleColor(ImGuiCol_SliderGrab,       { 0.40, 0.50, 0.80, 1.00 })
    imgui.PushStyleColor(ImGuiCol_SliderGrabActive, { 0.55, 0.65, 1.00, 1.00 })
    imgui.PushStyleColor(ImGuiCol_Separator,        { 0.20, 0.20, 0.28, 1.00 })
    imgui.PushStyleColor(ImGuiCol_Text,             { 0.85, 0.88, 0.95, 1.00 })

    imgui.PushStyleVar(ImGuiStyleVar_WindowRounding,   6.0)
    imgui.PushStyleVar(ImGuiStyleVar_WindowBorderSize, 1.0)
    imgui.PushStyleVar(ImGuiStyleVar_FrameRounding,    4.0)
end

local function PopWindowTheme()
    imgui.PopStyleVar(3)
    imgui.PopStyleColor(THEME_COLOR_COUNT)
end

local function BgColor()
    return cfg.bluemage_bg_color_r or 0.06, cfg.bluemage_bg_color_g or 0.07,
           cfg.bluemage_bg_color_b or 0.10, cfg.bluemage_bg_color_a or 0.96
end

-- =========================
-- Helpers
-- =========================
local function in_game_menu_open()
    local mm = AshitaCore and AshitaCore:GetMemoryManager()
    if not mm then return false end
    local interface = mm:GetInterfaceControl()
    if not interface then return false end
    return interface:GetMenuOpen() ~= 0
end

-- Player's BLU main-job level, or nil if BLU is not the main job. Uses the
-- party self-slot (index 0), matching how Renkei reads job/level here.
local function GetBluLevel()
    local mm = AshitaCore and AshitaCore:GetMemoryManager()
    if not mm then return nil end
    local party = mm:GetParty()
    if not party then return nil end
    local ok_job, job = pcall(function() return party:GetMemberMainJob(0) end)
    if not ok_job or job ~= BLU_JOB_ID then return nil end
    local ok_lvl, lvl = pcall(function() return party:GetMemberMainJobLevel(0) end)
    if not ok_lvl then return nil end
    return lvl
end

-- Player's current Blue Magic combat skill value (skill id 43), or nil if it
-- can't be read on this client. Handles the binding returning either a skill
-- object (with :GetSkill()) or a plain number.
local BLUE_MAGIC_SKILL_ID = 43
local function GetBlueSkill()
    local mm = AshitaCore and AshitaCore:GetMemoryManager()
    if not mm then return nil end
    local ok_p, player = pcall(function() return mm:GetPlayer() end)
    if not ok_p or not player then return nil end
    local ok, cs = pcall(function() return player:GetCombatSkill(BLUE_MAGIC_SKILL_ID) end)
    if not ok or cs == nil then return nil end
    if type(cs) == 'number' then return cs end
    local ok2, val = pcall(function() return cs:GetSkill() end)
    if ok2 and type(val) == 'number' then return val end
    return nil
end

-- Current zone id and its formatted name (matching learn-from zone strings),
-- or nil if not available / not catalogued.
local function GetCurrentZone()
    local mm = AshitaCore and AshitaCore:GetMemoryManager()
    if not mm then return nil, nil end
    local party = mm:GetParty()
    if not party then return nil, nil end
    local ok, zid = pcall(function() return party:GetMemberZone(0) end)
    if not ok or not zid or zid == 0 then return nil, nil end
    return zid, ZONES[zid]
end

-- Spells learnable in the given zone name: unlearned spells whose learn-from
-- data lists a mob in that zone. Returns an array of
-- { rec, mobs = { {mob, level}, ... } } (every mob for that spell in the zone).
local function SpellsInZone(zoneName)
    local out = {}
    if not zoneName then return out end
    for _, r in ipairs(SORTED) do
        if not learned[r.key] then
            local rows = LF.DATA[r.key]
            if rows then
                local mobs = {}
                for _, row in ipairs(rows) do
                    if row[3] == zoneName then
                        mobs[#mobs + 1] = { row[1], row[2] }
                    end
                end
                if #mobs > 0 then
                    out[#out + 1] = { rec = r, mobs = mobs }
                end
            end
        end
    end
    return out
end

local function CountLearned()
    local n = 0
    for _, r in ipairs(DB.SPELLS) do
        if learned[r.key] then n = n + 1 end
    end
    return n
end

-- Read the player's Blue Magic spellbook and mark each spell learned/unlearned
-- accordingly. This is the single source of truth for the checkmarks. Guarded
-- so it silently no-ops until the player is loaded (and if HasSpell is absent).
local function SyncFromSpellbook()
    if not learned then return end
    local mm = AshitaCore and AshitaCore:GetMemoryManager()
    if not mm then return end
    local ok_p, player = pcall(function() return mm:GetPlayer() end)
    if not ok_p or not player then return end

    for _, r in ipairs(DB.SPELLS) do
        local sid = SID[r.key]
        if sid then
            local ok, has = pcall(function() return player:HasSpell(sid) end)
            if not ok then
                -- HasSpell not available in this build; stop trying so we don't
                -- spam pcall every frame. Leave current state as-is.
                spellbook_ok = false
                return
            end
            learned[r.key] = has and true or false
        end
    end
end

-- Strip FFXI auto-translate / color control bytes so plain substring
-- matching works on the "learns" message.
local function CleanText(s)
    if type(s) ~= 'string' then return '' end
    s = s:gsub('[\30\31].', '')   -- color start/end + palette byte
    s = s:gsub('\7', '')          -- line break marker
    s = s:gsub('\127.', '')       -- auto-translate brackets
    s = s:gsub('%z', '')          -- stray nulls
    return s
end

-- Does this spell pass the current filter set?
local function PassesFilter(r, needle, bluLvl)
    if cfg.bluemage_hide_learned and learned[r.key] then return false end
    if cfg.bluemage_only_my_level and bluLvl and r.lvl > bluLvl then return false end
    if roleFilter  ~= 'All' and r.role  ~= roleFilter  then return false end
    if traitFilter ~= 'All' and r.trait ~= traitFilter then return false end
    if famFilter   ~= 'All' and r.fam   ~= famFilter   then return false end
    if needle and needle ~= '' then
        local hay = (r.name .. ' ' .. r.trait .. ' ' .. r.elem .. ' '
                     .. (r.fam or '') .. ' ' .. (r.prop or '')):lower()
        if not hay:find(needle, 1, true) then return false end
    end
    return true
end

-- =========================
-- Filter combo
-- =========================
local function FilterCombo(label, id, current, options, width)
    imgui.SetNextItemWidth(width)
    local changed = current
    if imgui.BeginCombo(id, label .. ': ' .. current) then
        -- `id` already carries a "##" prefix, so append it directly (a single
        -- "##") to each option; adding another "##" would create "###", which
        -- makes ImGui hash only the shared suffix and collide every item's ID.
        if imgui.Selectable('All' .. id, current == 'All') then changed = 'All' end
        for _, opt in ipairs(options) do
            if imgui.Selectable(opt .. id, current == opt) then changed = opt end
        end
        imgui.EndCombo()
    end
    return changed
end

-- =========================
-- Column layout helpers
-- =========================
local function SetupColumns(id)
    imgui.Columns(8, id, false)
    imgui.SetColumnWidth(0, CW_CHECK)
    imgui.SetColumnWidth(1, CW_MRL)
    imgui.SetColumnWidth(2, CW_LV)
    imgui.SetColumnWidth(3, CW_NAME)
    imgui.SetColumnWidth(4, CW_TYPE)
    imgui.SetColumnWidth(5, CW_TRAIT)
    imgui.SetColumnWidth(6, CW_FAM)
    imgui.SetColumnWidth(7, CW_TRK)
end

-- =========================
-- Learn-readiness status (for green/yellow/dim colouring)
--   green  : your Blue Magic skill already meets the learn requirement
--   yellow : you are a high enough level (>= MRL) but your skill is too low
--   dim    : you are below the level range for the spell
--   none   : BLU is not your main job, so we can't judge readiness
-- =========================
local STATUS_COL = {
    green  = { 0.45, 0.92, 0.52, 1.0 },
    yellow = { 0.96, 0.82, 0.36, 1.0 },
    dim    = { 0.55, 0.57, 0.66, 1.0 },
}

local function LearnStatus(key, bluLvl, skill)
    if bluLvl == nil then return 'none' end
    local mrl   = MRL[key]   or 999
    local reqsk = REQSK[key] or 0
    if skill ~= nil then
        if skill >= reqsk then return 'green' end   -- enough skill: learnable now
        if bluLvl >= mrl   then return 'yellow' end  -- in level range, skill too low
        return 'dim'
    end
    -- Skill couldn't be read: fall back to level vs MRL (no yellow state).
    if bluLvl >= mrl then return 'green' else return 'dim' end
end

-- =========================
-- Row (drawn inside an active 7-column context)
-- =========================
local function DrawSpellRow(r, bluLvl, skill)
    local isLearned = learned[r.key] and true or false
    local status    = LearnStatus(r.key, bluLvl, skill)
    local statusCol  = STATUS_COL[status]

    -- col 0: read-only learned indicator (driven by the player's spellbook).
    if isLearned then
        imgui.PushStyleColor(ImGuiCol_Text, { 0.45, 0.95, 0.55, 1.0 })
        imgui.Text('[X]')
    else
        imgui.PushStyleColor(ImGuiCol_Text, { 0.45, 0.48, 0.60, 1.0 })
        imgui.Text('[ ]')
    end
    imgui.PopStyleColor(1)
    imgui.NextColumn()

    -- Neutral base colour for the non-status columns.
    local baseCol = (status == 'dim') and { 0.50, 0.52, 0.62, 1.0 } or { 0.82, 0.85, 0.94, 1.0 }
    -- green = your skill is high enough now, yellow = in range but skill too
    -- low, dim = below the level range.
    local mrl = MRL[r.key]
    if mrl then
        imgui.PushStyleColor(ImGuiCol_Text, statusCol or { 0.62, 0.62, 0.70, 1.0 })
        imgui.Text(tostring(mrl))
        imgui.PopStyleColor(1)
    else
        imgui.PushStyleColor(ImGuiCol_Text, { 0.45, 0.48, 0.60, 1.0 })
        imgui.Text('-')
        imgui.PopStyleColor(1)
    end
    imgui.NextColumn()

    -- col 2: LVL (level the spell can be set / used)
    imgui.PushStyleColor(ImGuiCol_Text, (status == 'dim') and { 0.62, 0.56, 0.56, 1.0 } or { 0.70, 0.73, 0.85, 1.0 })
    imgui.Text(tostring(r.lvl))
    imgui.PopStyleColor(1)
    imgui.NextColumn()

    -- col 3: Spell name. Coloured by learn-readiness (green/yellow/dim); when
    -- BLU isn't your main job, falls back to the role colour. " *" = Horizon change.
    imgui.PushStyleColor(ImGuiCol_Text, statusCol or (ROLE_COLORS[r.role] or baseCol))
    if imgui.Selectable(r.name .. (r.hz and ' *' or '') .. '##nm_' .. r.key, selectedKey == r.key) then
        selectedKey = r.key
    end
    imgui.PopStyleColor(1)
    if imgui.IsItemHovered() then
        imgui.BeginTooltip()
        imgui.Text(r.name)
        imgui.Separator()
        imgui.PushStyleColor(ImGuiCol_Text, { 0.70, 0.73, 0.85, 1.0 })
        imgui.Text(('%s  -  %s'):format(
            (r.kind == 'Phys') and 'Physical' or 'Magical', r.role))
        imgui.Text(('Usable at Lv %d   -   Learn by Lv %s (capped skill)'):format(r.lvl, MRL[r.key] and tostring(MRL[r.key]) or '?'))
        imgui.Text(('Needs Blue Magic skill %d  -  skill+ gear can learn earlier'):format(REQSK[r.key] or 0))
        imgui.Text('Type: ' .. r.elem)
        imgui.Text('Trait when set: ' .. r.trait)
        imgui.Text('Effect / SC: ' .. (r.prop or '-'))
        imgui.Text('Learn from: ' .. ((r.fam and r.fam ~= '\226\128\148') and r.fam or 'not catalogued'))
        imgui.Text('MP: ' .. (r.mp and tostring(r.mp) or '?'))
        imgui.PopStyleColor(1)
        if r.hz then
            imgui.Separator()
            imgui.PushStyleColor(ImGuiCol_Text, { 1.00, 0.72, 0.35, 1.0 })
            imgui.Text('HorizonXI-specific change vs retail.')
            imgui.PopStyleColor(1)
        end
        imgui.Separator()
        imgui.PushStyleColor(ImGuiCol_Text, isLearned and { 0.55, 0.90, 0.60, 1.0 } or { 0.55, 0.58, 0.72, 1.0 })
        imgui.Text(isLearned and 'Learned' or 'Not yet learned')
        imgui.PopStyleColor(1)
        if not isLearned and status ~= 'none' then
            imgui.PushStyleColor(ImGuiCol_Text, statusCol or { 0.55, 0.58, 0.72, 1.0 })
            if status == 'green' then
                imgui.Text('Your skill is high enough - learnable now')
            elseif status == 'yellow' then
                imgui.Text('In level range - raise Blue Magic skill to learn')
            else
                imgui.Text('Below the level range for this spell')
            end
            imgui.PopStyleColor(1)
        end
        imgui.EndTooltip()
    end
    imgui.NextColumn()

    -- col 4: Type  ("P Slashing" / "M Fire")
    imgui.PushStyleColor(ImGuiCol_Text, (status == 'dim') and baseCol or (ELEM_COLORS[r.elem] or baseCol))
    imgui.Text(((r.kind == 'Phys') and 'P ' or 'M ') .. r.elem)
    imgui.PopStyleColor(1)
    imgui.NextColumn()

    -- col 5: Trait
    imgui.PushStyleColor(ImGuiCol_Text, baseCol)
    imgui.Text(r.trait == 'None' and '-' or r.trait)
    imgui.PopStyleColor(1)
    imgui.NextColumn()

    -- col 6: Learn-from family
    imgui.PushStyleColor(ImGuiCol_Text, baseCol)
    imgui.Text(r.fam or '\226\128\148')
    imgui.PopStyleColor(1)
    imgui.NextColumn()

    -- col 7: Tracking checkbox - clickable, user-controlled.
    local isTracked = tracked[r.key] and true or false
    imgui.PushStyleColor(ImGuiCol_Text, isTracked and { 0.55, 0.85, 1.00, 1.0 } or { 0.40, 0.43, 0.55, 1.0 })
    if imgui.Selectable((isTracked and '[X]##trk_' or '[ ]##trk_') .. r.key, isTracked) then
        tracked[r.key] = not isTracked
        settings.save()
    end
    imgui.PopStyleColor(1)
    if imgui.IsItemHovered() then
        imgui.SetTooltip(isTracked and 'Tracked - click to untrack' or 'Click to track this spell')
    end
    imgui.NextColumn()
end

-- =========================
-- Header row (column labels; fixed above the scroll area)
-- =========================
local function DrawHeaderRow()
    SetupColumns('##bm_hdr')
    imgui.PushStyleColor(ImGuiCol_Text, { 0.60, 0.63, 0.78, 1.0 })
    imgui.Text('');         imgui.NextColumn()
    imgui.Text('MRL');      imgui.NextColumn()
    imgui.Text('LVL');      imgui.NextColumn()
    imgui.Text('Spell');    imgui.NextColumn()
    imgui.Text('Type');     imgui.NextColumn()
    imgui.Text('Trait');    imgui.NextColumn()
    imgui.Text('Family');   imgui.NextColumn()
    imgui.Text('Tracking'); imgui.NextColumn()
    imgui.PopStyleColor(1)
    imgui.Columns(1)
    imgui.Separator()
end

-- =========================
-- Progress bar (manual; no imgui.ProgressBar in this binding)
-- =========================
local function DrawProgressBar(frac, w, h)
    local x, y = imgui.GetCursorScreenPos()
    local dl = imgui.GetWindowDrawList()
    dl:AddRectFilled({ x, y }, { x + w, y + h }, imgui.GetColorU32({ 0.14, 0.15, 0.20, 1.0 }))
    if frac > 0 then
        local col = (frac >= 1.0) and { 0.40, 0.85, 0.50, 1.0 } or { 0.35, 0.55, 0.95, 1.0 }
        dl:AddRectFilled({ x, y }, { x + w * frac, y + h }, imgui.GetColorU32(col))
    end
    dl:AddRect({ x, y }, { x + w, y + h }, imgui.GetColorU32({ 0.30, 0.33, 0.45, 1.0 }))
    imgui.Dummy({ w, h })
end

-- =========================
-- Hover mini-map. Two modes:
--   * Calibrated: if the zone has a `calibration` block, world coords are
--     mapped into 512-reference map space exactly like Boussole
--     (texX = x*scalingX + offsetX, texY = z*scalingY + offsetY), so the plot
--     matches the in-game map's orientation and proportions. If a real map
--     image is present at  <addon>/maps/<image>  it is drawn underneath the
--     markers (best-effort; any failure silently falls back to the grid).
--   * Fallback: a plain data-bounds grid (no calibration needed).
-- Returns true if it had data to draw.
-- =========================
local MAP_W, MAP_H, MAP_PAD = 240, 240, 10

local function u32(r, g, b, a)
    return imgui.GetColorU32({ r, g, b, a or 1.0 })
end

-- Lazy, guarded PNG loader. Returns a texture pointer usable as an ImGui image
-- id, or nil. Never throws; caches success/failure per file so we try once.
local _tex_cache = {}
local _cdef_done = false
local function load_map_texture(imageName)
    if not imageName or imageName == '' then return nil end
    if _tex_cache[imageName] ~= nil then
        return _tex_cache[imageName] or nil
    end
    local ok, tex = pcall(function()
        if not addon or not addon.path then return nil end
        local base = tostring(addon.path):gsub('[\\/]+$', '')
        local path = base .. '\\maps\\' .. imageName
        local f = io.open(path, 'rb'); if not f then return nil end; f:close()
        local ffi  = require('ffi')
        local d3d8 = require('d3d8')
        local dev  = d3d8.get_device()
        if not dev then return nil end
        if not _cdef_done then
            ffi.cdef[[
                int32_t D3DXCreateTextureFromFileA(void* device, const char* file, void** texture);
            ]]
            _cdef_done = true
        end
        local out = ffi.new('void*[1]')
        local hr = ffi.C.D3DXCreateTextureFromFileA(dev, path, out)
        if hr ~= 0 or out[0] == nil then return nil end
        return d3d8.gc_safe_release(ffi.cast('IDirect3DBaseTexture8*', out[0]))
    end)
    local result = ok and tex or nil
    _tex_cache[imageName] = result or false
    return result
end

local function DrawMobMap(zoneName, mobName)
    local zc = POS[zoneName]
    if not zc or not zc.mobs then return false end
    local pts = zc.mobs[mobName]
    if not pts or #pts == 0 then return false end

    -- Header (auto-sizes the tooltip).
    imgui.PushStyleColor(ImGuiCol_Text, { 0.85, 0.92, 1.00, 1.0 })
    imgui.Text(mobName)
    imgui.PopStyleColor(1)
    imgui.PushStyleColor(ImGuiCol_Text, { 0.62, 0.66, 0.80, 1.0 })
    imgui.Text(('%s   -   %d spawn point%s'):format(zoneName, #pts, (#pts == 1) and '' or 's'))
    imgui.PopStyleColor(1)

    local ox, oy = imgui.GetCursorScreenPos()
    imgui.Dummy({ MAP_W, MAP_H })
    local dl = imgui.GetWindowDrawList()

    local x0, y0 = ox, oy
    local x1, y1 = ox + MAP_W, oy + MAP_H
    local ix0, iy0 = x0 + MAP_PAD, y0 + MAP_PAD
    local ix1, iy1 = x1 - MAP_PAD, y1 - MAP_PAD
    local iw, ih = ix1 - ix0, iy1 - iy0

    -- Mob centroid (used to pick the right map floor and for the readout).
    local cx, cz = 0, 0
    for _, p in ipairs(pts) do cx = cx + p.x; cz = cz + p.z end
    cx = cx / #pts; cz = cz / #pts

    -- Choose a world -> inner-screen transform and (optionally) a background
    -- image, in priority order:
    --   1. LIVE client map for the floor that covers this mob (real calibration)
    --   2. shipped/user PNG at maps/<image> with fitted calibration
    --   3. fitted-calibration grid    4. data-bounds grid
    local cal = zc.calibration
    local to_screen
    local bg_id           -- imgui texture id to draw as background, or nil
    local bg_is_live = false

    local gm = gamemap and zc.zoneid and gamemap.get_best(zc.zoneid, cx, cz) or nil
    if gm and gm.entry then
        bg_id = gm.id
        bg_is_live = true
        local e = gm.entry
        to_screen = function(wx, wz)
            local rx, ry = gamemap.world_to_ref(e, wx, wz)  -- 0..512 ref space
            return ix0 + (rx / 512.0) * iw, iy0 + (ry / 512.0) * ih
        end
    elseif cal and cal.referenceSize and cal.referenceSize > 0 then
        local ref = cal.referenceSize
        to_screen = function(wx, wz)
            local tx = wx * cal.scalingX + cal.offsetX
            local ty = wz * cal.scalingY + cal.offsetY
            return ix0 + (tx / ref) * iw, iy0 + (ty / ref) * ih
        end
    else
        local b = zc.bounds
        local dx = (b.max_x - b.min_x); local dz = (b.max_z - b.min_z)
        if dx <= 0 or dz <= 0 then return false end
        to_screen = function(wx, wz)
            local u = (wx - b.min_x) / dx; local v = (wz - b.min_z) / dz
            if u < 0 then u = 0 elseif u > 1 then u = 1 end
            if v < 0 then v = 0 elseif v > 1 then v = 1 end
            return ix0 + u * iw, iy0 + v * ih
        end
    end

    -- Background: live client map, else a shipped/user PNG, else dark panel.
    if not bg_id and cal then bg_id = load_map_texture(cal.image) end
    dl:AddRectFilled({ x0, y0 }, { x1, y1 }, u32(0.07, 0.08, 0.12, 0.98), 6.0)
    local tex = bg_id
    if tex then
        local okimg = pcall(function()
            dl:AddImage(tex, { ix0, iy0 }, { ix1, iy1 })
        end)
        if not okimg then tex = nil end
    end
    dl:AddRect({ x0, y0 }, { x1, y1 }, u32(0.30, 0.36, 0.50, 0.9), 6.0)

    -- Grid (lighter when a real image is shown).
    local gcol = tex and u32(0.75, 0.80, 0.92, 0.10) or u32(0.20, 0.24, 0.34, 0.55)
    local N = 8
    for i = 0, N do
        local gx = ix0 + iw * (i / N)
        local gy = iy0 + ih * (i / N)
        dl:AddLine({ gx, iy0 }, { gx, iy1 }, gcol, 1.0)
        dl:AddLine({ ix0, gy }, { ix1, gy }, gcol, 1.0)
    end

    -- Compass.
    local cmp = u32(0.60, 0.65, 0.80, 0.9)
    local midx = (ix0 + ix1) * 0.5
    local midy = (iy0 + iy1) * 0.5
    dl:AddText({ midx - 4, y0 + 2 },  cmp, 'N')
    dl:AddText({ midx - 4, y1 - 16 }, cmp, 'S')
    dl:AddText({ x1 - 14, midy - 7 }, cmp, 'E')
    dl:AddText({ x0 + 4,  midy - 7 }, cmp, 'W')

    -- Markers: small red dots with a thin dark outline for contrast on the map.
    for _, p in ipairs(pts) do
        local sx, sy = to_screen(p.x, p.z)
        if sx < ix0 then sx = ix0 elseif sx > ix1 then sx = ix1 end
        if sy < iy0 then sy = iy0 elseif sy > iy1 then sy = iy1 end
        dl:AddCircleFilled({ sx, sy }, 2.2, u32(0.05, 0.02, 0.02, 0.85))  -- outline
        dl:AddCircleFilled({ sx, sy }, 1.3, u32(0.95, 0.15, 0.15, 1.0))   -- red dot
    end

    imgui.PushStyleColor(ImGuiCol_Text, { 0.50, 0.54, 0.68, 1.0 })
    imgui.Text(('center ~ (%d, %d)%s'):format(
        math.floor(cx + 0.5), math.floor(cz + 0.5),
        bg_is_live and '   [live map]' or (tex and '   [map]' or '')))
    imgui.PopStyleColor(1)

    return true
end

-- =========================
-- "Learned From" detail panel (bottom of the window)
-- =========================
local function DrawDetailPanel()
    local sel = selectedKey and DB.BY_KEY[selectedKey] or nil

    imgui.BeginChild('##bm_detail', { 0, DETAIL_HEIGHT })

    if not sel then
        imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
        imgui.Text('Click a spell name above to see where to learn it')
        imgui.Text('(monster, level, and zone).')
        imgui.PopStyleColor(1)
        imgui.EndChild()
        return
    end

    imgui.PushStyleColor(ImGuiCol_Text, { 0.80, 0.90, 1.00, 1.0 })
    imgui.Text('Learned From:  ' .. sel.name)
    imgui.PopStyleColor(1)

    imgui.PushStyleColor(ImGuiCol_Text, { 0.70, 0.73, 0.85, 1.0 })
    imgui.Text(('Family: %s     Type: %s %s     Usable Lv %d     Learnable Lv %s')
        :format(sel.fam or '\226\128\148', (sel.kind == 'Phys') and 'P' or 'M', sel.elem,
                sel.lvl, MRL[sel.key] and tostring(MRL[sel.key]) or '?'))
    imgui.PopStyleColor(1)
    imgui.Separator()

    local rows = LF.DATA[sel.key]
    if rows and #rows > 0 then
        imgui.Columns(3, '##bm_lf', false)
        imgui.SetColumnWidth(0, 150)
        imgui.SetColumnWidth(1, 60)
        imgui.PushStyleColor(ImGuiCol_Text, { 0.60, 0.63, 0.78, 1.0 })
        imgui.Text('Monster'); imgui.NextColumn()
        imgui.Text('Level');   imgui.NextColumn()
        imgui.Text('Zone');    imgui.NextColumn()
        imgui.PopStyleColor(1)
        for _, row in ipairs(rows) do
            imgui.PushStyleColor(ImGuiCol_Text, { 0.82, 0.85, 0.94, 1.0 })
            imgui.Text(row[1]); imgui.NextColumn()
            imgui.PopStyleColor(1)
            -- Hover the monster name to see its spawn points on a mini-map
            -- (only for zones we have position data for; West Ronfaure to start).
            if imgui.IsItemHovered() and POS[row[3]] and POS[row[3]].mobs[row[1]] then
                imgui.BeginTooltip()
                DrawMobMap(row[3], row[1])
                imgui.EndTooltip()
            end
            imgui.PushStyleColor(ImGuiCol_Text, { 0.70, 0.73, 0.85, 1.0 })
            imgui.Text(row[2]); imgui.NextColumn()
            imgui.PopStyleColor(1)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.72, 0.82, 0.72, 1.0 })
            imgui.Text(row[3]); imgui.NextColumn()
            imgui.PopStyleColor(1)
        end
        imgui.Columns(1)
    else
        imgui.PushStyleColor(ImGuiCol_Text, { 0.60, 0.63, 0.78, 1.0 })
        imgui.Text('Learn from the ' .. (sel.fam or 'listed') .. ' family.')
        imgui.PopStyleColor(1)
        imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
        imgui.Text('Specific mobs for this spell are being added.')
        imgui.PopStyleColor(1)
    end

    imgui.EndChild()
end

-- =========================
-- Module API
-- =========================
function M.init(host)
    cfg         = host.cfg
    vt          = host.vt
    settings    = host.settings
    helpers     = host.helpers
    default_cfg = host.default_config

    -- Bind the learned subtable (settings.load already merged defaults).
    if not cfg.bluemage_data then cfg.bluemage_data = M.default_data end
    if not cfg.bluemage_data.learned then cfg.bluemage_data.learned = T{} end
    learned = cfg.bluemage_data.learned

    -- Bind the user-selected "tracked" spells (persisted).
    if not cfg.bluemage_track_data then cfg.bluemage_track_data = M.default_track end
    if not cfg.bluemage_track_data.tracked then cfg.bluemage_track_data.tracked = T{} end
    tracked = cfg.bluemage_track_data.tracked

    -- Make sure every known spell has an entry (handles data additions).
    for _, r in ipairs(DB.SPELLS) do
        if learned[r.key] == nil then learned[r.key] = false end
        if tracked[r.key] == nil then tracked[r.key] = false end
    end

    -- Checkmarks are driven by the player's spellbook. Sync once now (runs
    -- again on a throttle in render as the player loads / learns spells).
    spellbook_ok    = true
    frame_counter   = 0
    last_sync_frame = 0
    SyncFromSpellbook()

    -- Bring up the "Action Learned!" splash helper.
    if BlueLearn then
        pcall(function() BlueLearn.init(host) end)
        -- Restrict the "Action Learned!" splash to real Blue Magic, so other
        -- jobs' spell learns (e.g. RDM scribing) don't trigger it.
        pcall(function()
            local set = {}
            for _, r in ipairs(DB.SPELLS) do set[r.name:lower()] = true end
            BlueLearn.set_valid_spells(set)
        end)
    end
end

-- =========================
-- Separate "tracker" window
-- =========================
local TRACK_WIN_W = 440
local TRACK_WIN_H = 380

-- Per-spell expand/collapse state in the tracker window.
local trk_expanded = {}

-- Leading number of a level string ("3-8" -> 3, "33" -> 33) for sorting.
local function MinLvl(s)
    local n = tostring(s):match('^%d+')
    return n and tonumber(n) or 0
end

-- A collapsible entry: header line (click to expand) + an indented mob list.
--   mobs      : array of { mob, level [, zone] }
--   show_zone : include the zone on each mob line (specific mode = all zones)
local function TrackerEntry(r, bluLvl, skill, mobs, show_zone, zone_name)
    local isL    = learned[r.key] and true or false
    local status = LearnStatus(r.key, bluLvl, skill)
    local open   = trk_expanded[r.key] and true or false

    local arrow = (#mobs > 0) and (open and '[-] ' or '[+] ') or '    '
    local label = arrow .. ('Lv%02d  '):format(r.lvl) .. r.name .. (isL and '  [X]' or '')

    imgui.PushStyleColor(ImGuiCol_Text, STATUS_COL[status] or { 0.82, 0.85, 0.94, 1.0 })
    if imgui.Selectable(label .. '##trkhdr_' .. r.key, open) then
        trk_expanded[r.key] = not open
    end
    imgui.PopStyleColor(1)

    if not open then return end
    if #mobs == 0 then
        imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
        imgui.Text('  learn from the ' .. (r.fam or 'listed') .. ' family')
        imgui.PopStyleColor(1)
        return
    end

    -- Sorted copy: Area, Mob, then Lvl. Zone mode has a single area (shown in
    -- the header) so it lists Mob, Lvl only.
    local rows = {}
    for _, m in ipairs(mobs) do rows[#rows + 1] = m end
    if show_zone then
        table.sort(rows, function(a, b)
            if (a[3] or '') ~= (b[3] or '') then return (a[3] or '') < (b[3] or '') end
            if a[1] ~= b[1] then return a[1] < b[1] end
            return MinLvl(a[2]) < MinLvl(b[2])
        end)
    else
        table.sort(rows, function(a, b)
            if a[1] ~= b[1] then return a[1] < b[1] end
            return MinLvl(a[2]) < MinLvl(b[2])
        end)
    end

    -- Aligned columns via measured text widths + absolute SameLine, so each
    -- column sits after the widest entry in the one before it (no overlap, and
    -- the level never gets squeezed into a fixed narrow column).
    local function tw(s)
        local w = imgui.CalcTextSize(s)
        return (type(w) == 'number') and w or 0
    end

    if show_zone then
        local maxA, maxM = 0, 0
        for _, m in ipairs(rows) do
            local a = tw('  ' .. (m[3] or '')); if a > maxA then maxA = a end
            local mm = tw(m[1]);                if mm > maxM then maxM = mm end
        end
        local mob_x = maxA + 16
        local lvl_x = mob_x + maxM + 16
        for _, m in ipairs(rows) do
            imgui.PushStyleColor(ImGuiCol_Text, { 0.62, 0.72, 0.60, 1.0 })  -- Area
            imgui.Text('  ' .. (m[3] or ''))
            imgui.PopStyleColor(1)
            imgui.SameLine(mob_x, 0)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.78, 0.80, 0.90, 1.0 })  -- Mob
            imgui.Text(m[1])
            imgui.PopStyleColor(1)
            do  -- hover the mob name for its spawn mini-map
                local zn = m[3] or zone_name
                if imgui.IsItemHovered() and zn and POS[zn] and POS[zn].mobs[m[1]] then
                    imgui.BeginTooltip(); DrawMobMap(zn, m[1]); imgui.EndTooltip()
                end
            end
            imgui.SameLine(lvl_x, 0)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.62, 0.66, 0.78, 1.0 })  -- Lvl
            imgui.Text('Lv ' .. tostring(m[2]))
            imgui.PopStyleColor(1)
        end
    else
        local maxM = 0
        for _, m in ipairs(rows) do
            local mm = tw('  ' .. m[1]); if mm > maxM then maxM = mm end
        end
        local lvl_x = maxM + 16
        for _, m in ipairs(rows) do
            imgui.PushStyleColor(ImGuiCol_Text, { 0.78, 0.80, 0.90, 1.0 })  -- Mob
            imgui.Text('  ' .. m[1])
            imgui.PopStyleColor(1)
            do  -- hover the mob name for its spawn mini-map
                local zn = m[3] or zone_name
                if imgui.IsItemHovered() and zn and POS[zn] and POS[zn].mobs[m[1]] then
                    imgui.BeginTooltip(); DrawMobMap(zn, m[1]); imgui.EndTooltip()
                end
            end
            imgui.SameLine(lvl_x, 0)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.62, 0.66, 0.78, 1.0 })  -- Lvl
            imgui.Text('Lv ' .. tostring(m[2]))
            imgui.PopStyleColor(1)
        end
    end
end

local function RenderTracker()
    if not cfg then return end
    if not tracked or not learned then return end
    local mode = cfg.bluemage_track_mode or 'off'
    if mode == 'off' then return end
    if cfg.bluemage_hide_on_menu and in_game_menu_open() then return end

    imgui.SetNextWindowSize({ TRACK_WIN_W, TRACK_WIN_H }, ImGuiCond_FirstUseEver)
    imgui.SetNextWindowPos({ cfg.bluemage_track_win_x or 910, cfg.bluemage_track_win_y or 200 }, ImGuiCond_FirstUseEver)

    PushWindowTheme(BgColor())
    local flags = 0
    if cfg.bluemage_lock_ui then
        flags = bit.bor(flags, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize)
    end

    local visible = { true }
    local begin_ok = imgui.Begin('Blue Magic Tracker', visible, flags)
    if begin_ok then
        local bluLvl = GetBluLevel()
        local skill  = GetBlueSkill()

        if mode == 'specific' then
            imgui.PushStyleColor(ImGuiCol_Text, { 0.80, 0.90, 1.00, 1.0 })
            imgui.Text('Tracked spells')
            imgui.PopStyleColor(1)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.50, 0.53, 0.66, 1.0 })
            imgui.Text('click a spell to list every mob / zone')
            imgui.PopStyleColor(1)
            imgui.Separator()
            imgui.BeginChild('##bm_trk_list', { 0, 0 })
            local any = false
            for _, r in ipairs(SORTED) do
                if tracked[r.key] then
                    any = true
                    TrackerEntry(r, bluLvl, skill, LF.DATA[r.key] or {}, true)
                end
            end
            if not any then
                imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
                imgui.Text('No spells tracked yet.')
                imgui.Text('Tick the "Trk" column in the main list.')
                imgui.PopStyleColor(1)
            end
            imgui.EndChild()

        elseif mode == 'zone' then
            local zid, zname = GetCurrentZone()
            imgui.PushStyleColor(ImGuiCol_Text, { 0.80, 0.90, 1.00, 1.0 })
            imgui.Text('Learnable in current zone')
            imgui.PopStyleColor(1)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.72, 0.82, 0.72, 1.0 })
            imgui.Text(zname or ('Zone ' .. tostring(zid or '?') .. ' (not catalogued)'))
            imgui.PopStyleColor(1)
            imgui.Separator()
            imgui.BeginChild('##bm_trk_list', { 0, 0 })
            local list = SpellsInZone(zname)
            if #list == 0 then
                imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
                imgui.Text('No unlearned spells to grab here.')
                imgui.PopStyleColor(1)
            else
                for _, item in ipairs(list) do
                    TrackerEntry(item.rec, bluLvl, skill, item.mobs, false, zname)
                end
            end
            imgui.EndChild()
        end

        -- Persist window position.
        local px, py = imgui.GetWindowPos()
        if px and py then
            if math.abs(px - (cfg.bluemage_track_win_x or 0)) > 0.5
            or math.abs(py - (cfg.bluemage_track_win_y or 0)) > 0.5 then
                cfg.bluemage_track_win_x = px
                cfg.bluemage_track_win_y = py
                settings.save()
            end
        end
    end
    imgui.End()
    PopWindowTheme()

    -- Closing the tracker window turns tracking off.
    if not visible[1] then
        cfg.bluemage_track_mode = 'off'
        settings.save()
    end
end

-- =========================
-- Settings tab (in-window config UI). Ported from the old Codex config
-- tab; the cross-module "Copy to all" and dispatcher kill-switch were
-- dropped since this is a standalone, single-window addon.
-- =========================
local function RenderConfigTab()
    -- Dark body background matching the main window.
    imgui.PushStyleColor(ImGuiCol_ChildBg, {
        cfg.bluemage_bg_color_r or 0.06, cfg.bluemage_bg_color_g or 0.07,
        cfg.bluemage_bg_color_b or 0.10, cfg.bluemage_bg_color_a or 0.96 })
    imgui.BeginChild('##blu_settings_body', { 0, 0 })

    -- ================= Action Learned text window (BlueLearn) =================
    imgui.PushStyleColor(ImGuiCol_Text, { 0.75, 0.78, 0.90, 1.0 })
    imgui.Text('Action Learned Text Window:')
    imgui.PopStyleColor(1)

    local bl_en = { cfg.bluelearn_enabled ~= false }
    if imgui.Checkbox('Enabled##bluelearn', bl_en) then
        cfg.bluelearn_enabled = bl_en[1]; settings.save()
    end
    if imgui.IsItemHovered() then
        imgui.SetTooltip('Show a centered splash with the spell name\nwhen YOU learn a Blue Magic spell.')
    end
    imgui.SameLine(148, 0)
    local bl_snd = { cfg.bluelearn_play_sound ~= false }
    if imgui.Checkbox('Play sound##bluelearn', bl_snd) then
        cfg.bluelearn_play_sound = bl_snd[1]; settings.save()
    end
    imgui.SameLine(0, 12)
    local bl_rules = { cfg.bluelearn_show_rules ~= false }
    if imgui.Checkbox('Rules##bluelearn', bl_rules) then
        cfg.bluelearn_show_rules = bl_rules[1]; settings.save()
    end
    if imgui.IsItemHovered() then imgui.SetTooltip('Draw the decorative lines above/below the text.') end

    imgui.PushItemWidth(150)
    local bl_dur = { cfg.bluelearn_duration or 3.5 }
    if imgui.SliderFloat('Duration (s)##bluelearn', bl_dur, 1.0, 8.0, '%.1f') then
        cfg.bluelearn_duration = bl_dur[1]; settings.save()
    end
    local bl_posy = { cfg.bluelearn_pos_y or 0.28 }
    if imgui.SliderFloat('Vertical pos##bluelearn', bl_posy, 0.05, 0.90, '%.2f') then
        cfg.bluelearn_pos_y = bl_posy[1]; settings.save()
    end
    if imgui.IsItemHovered() then imgui.SetTooltip('0.00 = top of screen, 0.50 = middle.') end
    local bl_fh = { math.floor(cfg.bluelearn_font_height or 46) }
    if imgui.SliderInt('Font size##bluelearn', bl_fh, 20, 80) then
        cfg.bluelearn_font_height = bl_fh[1]; settings.save()
    end
    imgui.PopItemWidth()

    -- Colors (stored as ARGB 0xAARRGGBB; edited as RGBA).
    local function bl_argb_to_rgba(v)
        v = v or 0
        local a = math.floor(v / 0x1000000) % 256
        local r = math.floor(v / 0x10000) % 256
        local g = math.floor(v / 0x100) % 256
        local b = v % 256
        return { r / 255, g / 255, b / 255, a / 255 }
    end
    local function bl_rgba_to_argb(t)
        local a = math.floor((t[4] or 1) * 255 + 0.5)
        local r = math.floor((t[1] or 0) * 255 + 0.5)
        local g = math.floor((t[2] or 0) * 255 + 0.5)
        local b = math.floor((t[3] or 0) * 255 + 0.5)
        return a * 0x1000000 + r * 0x10000 + g * 0x100 + b
    end
    local function bl_color(label, key, has_alpha)
        imgui.PushStyleColor(ImGuiCol_Text, { 0.70, 0.73, 0.85, 1.0 })
        imgui.AlignTextToFramePadding(); imgui.Text(label); imgui.PopStyleColor(1)
        imgui.SameLine(96, 0)
        local t = bl_argb_to_rgba(cfg[key])
        imgui.SetNextItemWidth(24)
        local flags = ImGuiColorEditFlags_NoInputs
        if has_alpha then flags = bit.bor(flags, ImGuiColorEditFlags_AlphaBar) end
        if imgui.ColorEdit4('##' .. key, t, flags) then
            cfg[key] = bl_rgba_to_argb(t); settings.save()
        end
    end
    bl_color('Top color', 'bluelearn_color_top', true)
    imgui.SameLine(0, 16)
    bl_color('Bottom', 'bluelearn_color_bottom', true)
    bl_color('Outline', 'bluelearn_outline_color', true)

    imgui.PushStyleColor(ImGuiCol_Button,        { 0.18, 0.24, 0.34, 1.0 })
    imgui.PushStyleColor(ImGuiCol_ButtonHovered, { 0.24, 0.32, 0.46, 1.0 })
    if imgui.Button('Test Splash##bluelearn', { 120, 0 }) then
        M.splash_preview('Cursed Sphere')
    end
    imgui.PopStyleColor(2)
    imgui.SameLine(0, 8)
    imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
    imgui.Text('( or /blutracker test [spell] )')
    imgui.PopStyleColor(1)

    imgui.Separator()

    -- Reset window settings (learned checkmarks come from the spellbook).
    imgui.PushStyleColor(ImGuiCol_Button,        { 0.20, 0.18, 0.28, 1.0 })
    imgui.PushStyleColor(ImGuiCol_ButtonHovered, { 0.30, 0.28, 0.42, 1.0 })
    if imgui.Button('Reset Settings##bluemage', { 120, 0 }) then
        M.reset_settings(default_cfg)
        if vt.cfg_bluemage_font_scale    then vt.cfg_bluemage_font_scale[1]    = cfg.bluemage_font_scale end
        if vt.cfg_bluemage_lock_ui       then vt.cfg_bluemage_lock_ui[1]       = cfg.bluemage_lock_ui end
        if vt.cfg_bluemage_hide_on_menu  then vt.cfg_bluemage_hide_on_menu[1]  = cfg.bluemage_hide_on_menu end
        if vt.cfg_bluemage_auto_learn    then vt.cfg_bluemage_auto_learn[1]    = cfg.bluemage_auto_learn end
        if vt.cfg_bluemage_hide_learned  then vt.cfg_bluemage_hide_learned[1]  = cfg.bluemage_hide_learned end
        if vt.cfg_bluemage_only_my_level then vt.cfg_bluemage_only_my_level[1] = cfg.bluemage_only_my_level end
        if vt.cfg_bluemage_bg_color then
            vt.cfg_bluemage_bg_color[1] = cfg.bluemage_bg_color_r
            vt.cfg_bluemage_bg_color[2] = cfg.bluemage_bg_color_g
            vt.cfg_bluemage_bg_color[3] = cfg.bluemage_bg_color_b
            vt.cfg_bluemage_bg_color[4] = cfg.bluemage_bg_color_a
        end
    end
    imgui.PopStyleColor(2)

    imgui.EndChild()
    imgui.PopStyleColor(1)   -- ChildBg
end

function M.render()
    if not cfg then return end

    -- Drive the "Action Learned!" splash fade/queue every frame, before any
    -- of the window early-returns below.
    if BlueLearn then pcall(function() BlueLearn.render() end) end

    -- Keep the learned checkmarks in sync with the player's spellbook. Runs
    -- regardless of which windows are open.
    if spellbook_ok then
        frame_counter = frame_counter + 1
        if frame_counter - last_sync_frame >= SYNC_INTERVAL then
            last_sync_frame = frame_counter
            SyncFromSpellbook()
        end
    end

    -- The separate tracker window renders independently of the main window
    -- (it shows whenever the track mode is not 'off').
    RenderTracker()

    if not cfg.bluemage_open then return end
    if cfg.bluemage_hide_on_menu and in_game_menu_open() then return end

    imgui.SetNextWindowSize({ WINDOW_WIDTH, WINDOW_HEIGHT }, ImGuiCond_FirstUseEver)
    imgui.SetNextWindowPos({ cfg.bluemage_win_x or 340, cfg.bluemage_win_y or 200 }, ImGuiCond_FirstUseEver)

    PushWindowTheme(BgColor())

    local flags = ImGuiWindowFlags_NoScrollbar
    if cfg.bluemage_lock_ui then
        flags = bit.bor(flags, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize)
    end

    local visible = { cfg.bluemage_open }
    local title = 'Blue Magic Tracker - V ' .. tostring((addon and addon.version) or '1.0')
    local begin_ok = imgui.Begin(title, visible, flags)

    -- Title-bar gear jumps to the in-window Settings tab.
    if helpers and helpers.draw_titlebar_gear then
        helpers.draw_titlebar_gear('blu', 1.0, function()
            if vt then vt._want_settings_tab = true end
        end)
    end

    if begin_ok and imgui.BeginTabBar('##blu_main_tabs', ImGuiTabBarFlags_None) then
    if imgui.BeginTabItem('Spells') then
        local bluLvl  = GetBluLevel()
        local skill   = GetBlueSkill()
        local total   = DB.COUNT
        local nLearn  = CountLearned()
        local frac    = (total > 0) and (nLearn / total) or 0

        -- ---- Progress ----
        imgui.PushStyleColor(ImGuiCol_Text, { 0.80, 0.90, 1.00, 1.0 })
        if bluLvl then
            if skill then
                imgui.Text(('Blue Mage   -   Lv %d   -   Blue Magic Skill %d'):format(bluLvl, skill))
            else
                imgui.Text(('Blue Mage   -   Lv %d'):format(bluLvl))
            end
        else
            imgui.Text('Blue Mage')
            imgui.SameLine(0, 8)
            imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
            imgui.Text('(set BLU as main job to see learn readiness)')
            imgui.PopStyleColor(1)
        end
        imgui.PopStyleColor(1)

        imgui.PushStyleColor(ImGuiCol_Text, { 0.70, 0.73, 0.85, 1.0 })
        imgui.Text(('Learned  %d / %d  (%d%%)'):format(nLearn, total, math.floor(frac * 100 + 0.5)))
        imgui.PopStyleColor(1)
        DrawProgressBar(frac, WINDOW_WIDTH - 24, 10)

        imgui.Spacing()

        -- ---- Filters ----
        -- Line 1: search box + learned/level toggles.
        imgui.SetNextItemWidth(180)
        imgui.InputText('##bm_search', searchBuf, 64)
        if imgui.IsItemHovered() then imgui.SetTooltip('Search name / trait / element / family') end
        imgui.SameLine(0, 12)
        local hl = { cfg.bluemage_hide_learned or false }
        if imgui.Checkbox('Hide learned', hl) then
            cfg.bluemage_hide_learned = hl[1]; settings.save()
        end
        imgui.SameLine(0, 10)
        local ol = { cfg.bluemage_only_my_level or false }
        if imgui.Checkbox('<= my level', ol) then
            cfg.bluemage_only_my_level = ol[1]; settings.save()
        end
        if imgui.IsItemHovered() then imgui.SetTooltip('Only show spells at or below your BLU level.') end

        -- Line 2: tracking mode + the sort/filter dropdowns.
        do
            local curMode  = cfg.bluemage_track_mode or 'off'
            local curLabel = 'Off'
            for _, m in ipairs(TRACK_MODES) do if m[1] == curMode then curLabel = m[2] end end
            imgui.SetNextItemWidth(140)
            if imgui.BeginCombo('##bm_track', 'Track: ' .. curLabel) then
                for _, m in ipairs(TRACK_MODES) do
                    if imgui.Selectable(m[2] .. '##bm_track', curMode == m[1]) then
                        cfg.bluemage_track_mode = m[1]
                        settings.save()
                    end
                end
                imgui.EndCombo()
            end
            if imgui.IsItemHovered() then
                imgui.SetTooltip('Tracker window:\nSpecific = spells you tick in the Trk column\n'
                    .. 'Zone = unlearned spells learnable in your current zone\nOff = hide the tracker')
            end
        end
        imgui.SameLine(0, 6)
        roleFilter  = FilterCombo('Role',  '##bm_role',  roleFilter,  DB.ROLES,    114)
        imgui.SameLine(0, 6)
        famFilter   = FilterCombo('Fam',   '##bm_fam',   famFilter,   DB.FAMILIES, 114)
        imgui.SameLine(0, 6)
        traitFilter = FilterCombo('Trait', '##bm_trait', traitFilter, DB.TRAITS,   150)

        imgui.Separator()

        -- ---- Column headers (fixed above the scroll area) ----
        DrawHeaderRow()

        -- ---- Scrollable list ----
        local needle = (searchBuf[1] or ''):lower()

        -- Height for the scroll region: window height minus the top block,
        -- the detail panel, and the footer. GetWindowSize returns (w, h) here.
        local _, winH = imgui.GetWindowSize()
        local listH = (winH or WINDOW_HEIGHT) - 178 - DETAIL_HEIGHT - FOOTER_HEIGHT
        if listH < 80 then listH = 80 end

        imgui.BeginChild('##bm_list', { 0, listH })

        SetupColumns('##bm_rows')
        local shown = 0
        for _, r in ipairs(SORTED) do
            if PassesFilter(r, needle, bluLvl) then
                DrawSpellRow(r, bluLvl, skill)
                shown = shown + 1
            end
        end
        imgui.Columns(1)

        if shown == 0 then
            imgui.PushStyleColor(ImGuiCol_Text, { 0.55, 0.58, 0.72, 1.0 })
            imgui.Text('No spells match the current filters.')
            imgui.PopStyleColor(1)
        end

        imgui.EndChild()

        -- ---- Learned-from detail panel ----
        imgui.Separator()
        DrawDetailPanel()

        -- ---- Footer ----
        imgui.Separator()
        imgui.PushStyleColor(ImGuiCol_Text, { 0.50, 0.53, 0.66, 1.0 })
        imgui.Text(('Showing %d'):format(shown))
        imgui.PopStyleColor(1)
        imgui.SameLine(0, 10)
        imgui.PushStyleColor(ImGuiCol_Text, { 0.50, 0.53, 0.66, 1.0 })
        imgui.Text('MRL:')
        imgui.PopStyleColor(1)
        imgui.SameLine(0, 6)
        imgui.PushStyleColor(ImGuiCol_Text, STATUS_COL.green)
        imgui.Text('Green = Learnable')
        imgui.PopStyleColor(1)
        imgui.SameLine(0, 6)
        imgui.PushStyleColor(ImGuiCol_Text, { 0.50, 0.53, 0.66, 1.0 })
        imgui.Text('|')
        imgui.PopStyleColor(1)
        imgui.SameLine(0, 6)
        imgui.PushStyleColor(ImGuiCol_Text, STATUS_COL.yellow)
        imgui.Text('Yellow = Raise Skill lvl to Learn')
        imgui.PopStyleColor(1)
        imgui.SameLine(0, 10)
        imgui.PushStyleColor(ImGuiCol_Text, { 0.50, 0.53, 0.66, 1.0 })
        imgui.Text(spellbook_ok and '-   click a name for locations' or '-   spellbook read unavailable')
        imgui.PopStyleColor(1)

        imgui.Text('')   -- extra line of spacing below the legend

        imgui.EndTabItem()
    end  -- Spells tab

    -- Settings tab. The gear / "/blutracker config" set vt._want_settings_tab so we
    -- programmatically select it here on the next frame.
    local set_flags = 0
    if vt and vt._want_settings_tab then
        set_flags = (type(ImGuiTabItemFlags_SetSelected) == 'number')
                    and ImGuiTabItemFlags_SetSelected or 2
        vt._want_settings_tab = false
    end
    if imgui.BeginTabItem('Settings', nil, set_flags) then
        RenderConfigTab()
        imgui.EndTabItem()
    end

    imgui.EndTabBar()

    -- Persist window position (applies regardless of the active tab).
    local px, py = imgui.GetWindowPos()
    if px and py then
        if math.abs(px - (cfg.bluemage_win_x or 0)) > 0.5
        or math.abs(py - (cfg.bluemage_win_y or 0)) > 0.5 then
            cfg.bluemage_win_x = px
            cfg.bluemage_win_y = py
            settings.save()
        end
    end
    end  -- if begin_ok and BeginTabBar
    imgui.End()

    PopWindowTheme()

    -- Sync close-button click back to cfg.
    if visible[1] ~= cfg.bluemage_open then
        cfg.bluemage_open = visible[1]
        if vt and vt.cfg_bluemage_open then vt.cfg_bluemage_open[1] = cfg.bluemage_open end
        settings.save()
    end
end

function M.command(e)
    -- Let the splash helper claim "/blutracker test*" first (else returns false).
    if BlueLearn then
        local ok, handled = pcall(function() return BlueLearn.command(e) end)
        if ok and handled then return true end
    end
    local a = e.command:lower():args()
    if #a == 0 then return false end
    if a[1] == '/blutracker' or a[1] == '/blut' then
        e.blocked = true
        if a[2] == 'config' or a[2] == 'settings' then
            cfg.bluemage_open = true
            if vt and vt.cfg_bluemage_open then vt.cfg_bluemage_open[1] = cfg.bluemage_open end
            if vt then vt._want_settings_tab = true end
            settings.save()
        else
            cfg.bluemage_open = not cfg.bluemage_open
            if vt and vt.cfg_bluemage_open then vt.cfg_bluemage_open[1] = cfg.bluemage_open end
            settings.save()
        end
        return true
    end
    return false
end

-- Fallback only. When the spellbook read works it is authoritative and this
-- does nothing. On any client where IPlayer:HasSpell is unavailable
-- (spellbook_ok == false), this watches chat for the "learns <Spell>" message
-- and marks the spell so the tracker still updates as you learn.
function M.text_in(e)
    -- Feed the "Action Learned!" splash first (independent of the fallback).
    if BlueLearn then pcall(function() BlueLearn.text_in(e) end) end

    if not cfg or spellbook_ok then return end
    if cfg.bluemage_auto_learn == false then return end
    local msg = e.message or e.message_modified or e.text or ''
    local clean = CleanText(msg)
    if not clean:lower():find('learn', 1, true) then return end

    for _, r in ipairs(DB.SPELLS) do
        if clean:find(r.name, 1, true) then
            if not learned[r.key] then
                learned[r.key] = true
                print(('[BluTracker] Marked "%s" learned (%d/%d).')
                    :format(r.name, CountLearned(), DB.COUNT))
            end
            return
        end
    end
end

-- Preview the "Action Learned!" splash (called from the config tab's button).
function M.splash_preview(spell)
    if BlueLearn then pcall(function() BlueLearn.preview(spell) end) end
end

function M.unload()
    if BlueLearn then pcall(function() BlueLearn.unload() end) end
    if settings then settings.save() end
end

-- Reset the BlueMage window settings to defaults (from the config tab).
-- Learned checkmarks are read from the spellbook and have no reset.
function M.reset_settings(default_config)
    cfg.bluemage_font_scale    = default_config.bluemage_font_scale
    cfg.bluemage_lock_ui       = default_config.bluemage_lock_ui
    cfg.bluemage_hide_on_menu  = default_config.bluemage_hide_on_menu
    cfg.bluemage_auto_learn    = default_config.bluemage_auto_learn
    cfg.bluemage_hide_learned  = default_config.bluemage_hide_learned
    cfg.bluemage_only_my_level = default_config.bluemage_only_my_level
    cfg.bluemage_track_mode    = default_config.bluemage_track_mode
    cfg.bluemage_bg_color_r    = default_config.bluemage_bg_color_r
    cfg.bluemage_bg_color_g    = default_config.bluemage_bg_color_g
    cfg.bluemage_bg_color_b    = default_config.bluemage_bg_color_b
    cfg.bluemage_bg_color_a    = default_config.bluemage_bg_color_a
    -- "Action Learned!" splash appearance
    cfg.bluelearn_enabled       = default_config.bluelearn_enabled
    cfg.bluelearn_play_sound    = default_config.bluelearn_play_sound
    cfg.bluelearn_show_rules    = default_config.bluelearn_show_rules
    cfg.bluelearn_duration      = default_config.bluelearn_duration
    cfg.bluelearn_pos_y         = default_config.bluelearn_pos_y
    cfg.bluelearn_font_height   = default_config.bluelearn_font_height
    cfg.bluelearn_color_top     = default_config.bluelearn_color_top
    cfg.bluelearn_color_bottom  = default_config.bluelearn_color_bottom
    cfg.bluelearn_outline_color = default_config.bluelearn_outline_color
    settings.save()
end

return M
